module LexToGeniXML (headerGenXML, formatLexGenXML)

where

import Dtypes
import Generic
import System.Time
import Data.List
import XMLprint


-- normalized functions for pretty printing
headerGenXML :: ClockTime -> String -> String
headerGenXML time pname =
    headerGeniXML time pname

formatLexGenXML :: [LexEntry] -> ClockTime -> String -> String -> String -> String -> String
formatLexGenXML lex _ _ _ _ _ =
    printXML (formatLexGeniXML lex) ""
----------


headerGeniXML :: ClockTime -> String -> String
headerGeniXML t pname = 
    let time = calendarTimeToString (toUTCTime t)
	in "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n" ++ "<!-- lexicon generated by "++pname++" at "++time++"-->\n\n"


formatLexGeniXML :: [LexEntry] -> XMLelem
formatLexGeniXML lex =
        let l = sort lex
	    in --concatMap (\x -> convertEntry x) l
	      Elem {tag      = "lexicon",
	      features = [],
	      datas    = "",
	      children = [Elem {tag      = "lemmas",
				features = [],
				datas    = "",
				children = 
				map (\x -> convertEntryXML x) l }]}


convertEntryXML :: LexEntry -> XMLelem
convertEntryXML e =
    Elem {
          tag      = "lemma",
          features = [("family", (family e))] ++ [("name", (lemma e))],
          datas    = "",
          children = [(getEquations (equations e))] ++ [(getCoanchors (coanchors e))]
                     ++ [(getInterface (iface e))] ++ [(convertFilterXML (family e) (filters e))]
                     ++ [(convertSem (sem e))]
         }


getEquations :: [Equa] -> XMLelem
getEquations eq =
    Elem {tag      = "equations",
	  features = [],
	  datas    = "",
	  children = map (\x -> convertEquaXML x) eq
         }


convertEquaXML :: Equa -> XMLelem
convertEquaXML e =
    let (fs, sn) = (snd3 e) 
        nodename =  case (fst3 e) of "anchor" -> "anchor"
                                     "anc"    -> "anchor"
                                     _        -> (fst3 e)
        fsname   =  case fs of "" -> "bot"
                               _  -> fs
        in 
        Elem {tag      = "equation",
	                 features = [("type", fsname),("node_id", nodename)],
	                 datas    = "",
	                 children = [Elem {tag      = "fs",
			                   features = [],
			                   datas    = "",
			                   children = [Elem {tag      = "f",
					                     features = [("name",sn)],
					                     datas    = "",
					                     children = [convertVal (thd3 e)]}]}]}



convertVal :: Val -> XMLelem
convertVal v =
    case v of Const (x:y:xs) -> Elem {tag      = "vAlt",
				      features = [],
				      datas    = "",
				      children = 
				      map (\e -> convertVal (Const [e])) (x:y:xs)} 
	      _ -> Elem {tag      = "sym",
			 features = [("value",(show v))],
			 datas    = "",
			 children = []}


getCoanchors :: [Coanchor] -> XMLelem
getCoanchors co =
    Elem {tag      = "coanchors",
	  features = [],
	  datas    = "",
	  children = map (\x -> convertCoanchorXML x) co
         }


convertCoanchorXML :: Coanchor -> XMLelem
convertCoanchorXML (node,lex,cat) =
    Elem {tag      = "coanchor",
	  features = [("type", "top"),("node_id", node)],
	  datas    = "",
	  children = [Elem {tag      = "fs",
			    features = [],
			    datas    = "",
			    children = [Elem {tag      = "f",
					      features = [("name","lex")],
					      datas    = "",
					      children = [convertVal (Const [lex])]}] ++
                                       [Elem {tag      = "f",
					      features = [("name","cat")],
					      datas    = "",
					      children = [convertVal (Const [cat])]}
                                       ]
                           }
                     ]
         }


getInterface :: FS -> XMLelem
getInterface iface =
    Elem {tag      = "interface",
	  features = [],
	  datas    = "",
	  children = [
                      Elem {tag      = "fs",
			    features = [],
			    datas    = "",
			    children = map (\x -> convertAttVal x) iface
                           }
                     ]
         }


convertAttVal :: AVPair -> XMLelem
convertAttVal av =
    Elem {tag      = "f",
		     features = [("name",(fst av))],
		     datas    = "",
		     children = [convertVal (snd av)]}


convertFilterXML :: String -> FS -> XMLelem
convertFilterXML fam fil =
        Elem {tag      = "filter",
	      features = [],
	      datas    = "",
	      children = [
                          Elem {tag      = "fs",
			        features = [],
			        datas    = "",
			        children = [Elem {tag      = "f",
					          features = [("name", "family")],
					          datas    = "",
					          children = [convertVal (Const [fam])] 
                                                 }] ++
                                           (map (\x -> convertAttVal x) fil)
                               }
                         ]
             }
    

convertSem :: Sem -> XMLelem
convertSem s =
        Elem {tag      = "semantics",
	      features = [],
	      datas    = "",
	      children = map (\x -> convertLit x) s
             }


convertLit :: Lit -> XMLelem
convertLit l =
        Elem {tag      = "literal",
	      features = [("label", valToString (fst3 l))] ++ [("predicate", valToString (snd3 l))],
	      datas    = "",
	      children = [
                          Elem {tag      = "args",
			        features = [],
			        datas    = "",
			        children = (map (\x -> convertVal x) (thd3 l))
                               }
                         ]
             }
